### ISSUE TITLE
Equivalent to runtypes.Static<...>

### ISSUE THREAD

**Issue by freshgum-bubbles** [adwher/typecheck#11]
I'm a huge fan of runtypes, which is another runtime type validation library.
One important feature of it is that it can convert runtime type schemas to
compile-time ones through its `Static` type.  Does this library have an equivalent type?

## Example

```ts
import { Static, Record } from 'runtypes'; // NPM

export const Duck = Record({
  isADuck: true
});
export type Duck = Static<typeof Duck>;
```

The "name the type the same as the runtime type" pattern is actually one I use a lot.
Not sure what the official name for it is (name collision?), but it's really cool :D

(No pressure to implement this, of course :D)

**Comment by adwher** [comment]
Thank you for taking the time to found my project. Going back to your question: yes, we do have a "describer" to be used on **TypeScript**, you can [find it as `Describe`](https://github.com/adwher/typecheck/blob/8f38c18b85a87aab71b949302476986c2644c43a/schema.ts#L90).

> Now that you mentioned I think we should document it a little bit further

```typescript
import * as k from "@adwher/typecheck"

export const EmailSchema = k.pipe(k.string(), k.email());

// Creates a type based on the constant "EmailSchema" which should be equivalent to "string".
export type EmailSchema = k.Describe<typeof EmailSchema>;
```
